[build]
builder = "DOCKERFILE"
watchPatterns = ["/apps/web/**"]
dockerfilePath = "/apps/web/Dockerfile"

[deploy]
numReplicas = 1
healthcheckPath = "/health"
healthcheckTimeout = 300
sleepApplication = true
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
