app = 'sigle-lens-testnet-server'
primary_region = 'sjc'

[build]
image = "ghcr.io/sigle/sigle-lens/server:main"

[env]
  PORT = 3000

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
