// This file is auto-generated by @hey-api/openapi-ts

export type GetResponse = unknown;

export type GetHealthResponse = unknown;

export type GetApiPostsByPostIdData = {
    postId: string;
};

export type GetApiPostsByPostIdResponse = {
    id: string;
    title: string;
    content?: string;
    metaTitle?: string;
    metaDescription?: string;
    coverImage?: string;
    createdAt?: string;
};

export type PostApiPostsByPostIdUpdateData = {
    postId: string;
    requestBody: {
        title: string;
        content: string;
        metaTitle?: string;
        metaDescription?: string;
        coverImage?: string;
    };
};

export type PostApiPostsByPostIdUpdateResponse = {
    id: string;
};

export type PostApiPostsCreateResponse = {
    id: string;
};

export type GetApiPostsListResponse = Array<{
    id: string;
    title: string;
    content?: string;
    metaTitle?: string;
    metaDescription?: string;
    coverImage?: string;
    createdAt?: string;
    updatedAt?: string;
}>;

export type PostApiProfileUploadMetadataData = {
    requestBody: {
        /**
         * Profile metadata
         */
        metadata?: {
            [key: string]: unknown;
        };
    };
};

export type PostApiProfileUploadMetadataResponse = {
    /**
     * Arweave transaction ID
     */
    id: string;
};

export type GetNitroOpenapiJsonResponse = unknown;

export type GetNitroScalarResponse = unknown;

export type GetNitroSwaggerResponse = unknown;

export type $OpenApiTs = {
    '': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: unknown;
            };
        };
    };
    '/health': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: unknown;
            };
        };
    };
    '/api/posts/{postId}': {
        get: {
            req: {
                postId: string;
            };
            res: {
                /**
                 * Post entry.
                 */
                default: {
                    id: string;
                    title: string;
                    content?: string;
                    metaTitle?: string;
                    metaDescription?: string;
                    coverImage?: string;
                    createdAt?: string;
                };
            };
        };
    };
    '/api/posts/{postId}/update': {
        post: {
            req: {
                postId: string;
                requestBody: {
                    title: string;
                    content: string;
                    metaTitle?: string;
                    metaDescription?: string;
                    coverImage?: string;
                };
            };
            res: {
                /**
                 * Post updated.
                 */
                default: {
                    id: string;
                };
            };
        };
    };
    '/api/posts/create': {
        post: {
            res: {
                /**
                 * Post created.
                 */
                default: {
                    id: string;
                };
            };
        };
    };
    '/api/posts/list': {
        get: {
            res: {
                /**
                 * Posts list.
                 */
                default: Array<{
                    id: string;
                    title: string;
                    content?: string;
                    metaTitle?: string;
                    metaDescription?: string;
                    coverImage?: string;
                    createdAt?: string;
                    updatedAt?: string;
                }>;
            };
        };
    };
    '/api/profile/upload-metadata': {
        post: {
            req: {
                requestBody: {
                    /**
                     * Profile metadata
                     */
                    metadata?: {
                        [key: string]: unknown;
                    };
                };
            };
            res: {
                /**
                 * Metadata uploaded
                 */
                default: {
                    /**
                     * Arweave transaction ID
                     */
                    id: string;
                };
            };
        };
    };
    '/_nitro/openapi.json': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: unknown;
            };
        };
    };
    '/_nitro/scalar': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: unknown;
            };
        };
    };
    '/_nitro/swagger': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: unknown;
            };
        };
    };
};