// This file is auto-generated by @hey-api/openapi-ts

export type $OpenApiTs = {
    '': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: unknown;
            };
        };
    };
    '/health': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: unknown;
            };
        };
    };
    '/api/posts/{postId}': {
        get: {
            req: {
                postId: string;
            };
            res: {
                /**
                 * Post entry.
                 */
                200: {
                    id: string;
                    title: string;
                    content?: string;
                    metaTitle?: string;
                    metaDescription?: string;
                    coverImage?: string;
                    createdAt?: string;
                };
            };
        };
    };
    '/api/posts/{postId}/update': {
        post: {
            req: {
                postId: string;
                requestBody: {
                    title: string;
                    content: string;
                    metaTitle?: string;
                    metaDescription?: string;
                    coverImage?: string;
                };
            };
            res: {
                /**
                 * Post updated.
                 */
                200: {
                    id: string;
                };
            };
        };
    };
    '/api/posts/create': {
        post: {
            res: {
                /**
                 * Post created.
                 */
                200: {
                    id: string;
                };
            };
        };
    };
    '/api/profile/upload-metadata': {
        post: {
            req: {
                requestBody: {
                    /**
                     * Profile metadata
                     */
                    metadata?: {
                        [key: string]: unknown;
                    };
                };
            };
            res: {
                /**
                 * Metadata uploaded
                 */
                200: {
                    /**
                     * Arweave transaction ID
                     */
                    id: string;
                };
            };
        };
    };
    '/_nitro/openapi.json': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: unknown;
            };
        };
    };
    '/_nitro/scalar': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: unknown;
            };
        };
    };
    '/_nitro/swagger': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: unknown;
            };
        };
    };
};